version: '3.4'

services:
  galiciaseguros.iaas.service.template.ddd.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - SwaggerSettings__ServiceName=Api Service