version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "SERVICE_SQLSERVER"
    environment:
      - SA_PASSWORD=G@lic1aS3guros
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - galiciaseguros_sqldata:/var/opt/mssql
  galiciaseguros.iaas.service.template.ddd.api:
    image: ${DOCKER_REGISTRY-}galiciasegurosiaasservicetemplatedddapi
    container_name: "SERVICE_API"
    build:
      context: .
      dockerfile: src/GaliciaSeguros.IaaS.Service.Template.DDD.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - SwaggerSettings__ServiceName=Api Service
    ports:
      - "5156:80"
      - "7156:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sqlserver 
volumes:
  galiciaseguros_sqldata:
    external: false      