version: '3.4'

services:
  mongo:
    image: mongo
    container_name: "DB.MONGO"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: "DB.MONGO.MGM"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo      
  sql1:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "DB.SQLSERVER"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "admin"
    ports:
      - "1433:1433"
  galiciaseguros.iaas.service.template.ddd.api:
    container_name: "SERVICE.API"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5156:80"
      - "7156:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - mongo